version: '3'
services:
  express-app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "9000:9000"
    command: npm start
    environment:
      NODE_ENV: production
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SATDB
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: your-root-password
